#!/bin/sh

# List all executables on PATH
# https://unix.stackexchange.com/questions/120786/list-all-binaries-from-path
{
	set -f
	IFS=:
	for d in $PATH; do
		set +f
		[ -n "$d" ] || d=.
		for f in "$d"/.[ "$d"/..?* "$d"/*; do
			[ -f "$f" ] && [ -x "$f" ] && printf '%s\n' "${f##*/}"
		done
	done
} | sort
