#!/bin/sh

target_dir="$XDG_CONFIG_HOME/rc.d"
target="$target_dir/40-brew.sh"
command="env SHELL=/bin/sh /opt/homebrew/bin/brew shellenv"
tmp="$target.$$"

if ! [ -x /opt/homebrew/bin/brew ]; then
	echo "/opt/homebrew/bin/brew is not available; skipping generated brew rc.d file" >&2
	exit 0
fi

mkdir -p "$target_dir"
{
	printf '%s\n' '#!/bin/sh'
	printf '%s\n' '# This file is generated from shell-loadable output produced by a CLI tool.'
	printf '%s\n' '# Generated by CLI tool: Homebrew'
	printf '%s\n' "# Command: $command"
	printf '\n'
	env SHELL=/bin/sh /opt/homebrew/bin/brew shellenv
} > "$tmp" || {
	rm -f "$tmp"
	exit 1
}

chmod +x "$tmp"
[ -L "$target" ] && rm -f "$target"
mv "$tmp" "$target"
