#!/bin/sh

# the XDG setup needs to be loaded manually during startup, the first file
# zsh laods under our control is ~/.zshenv here, I tell it where it can find
# the zshrc file. But both are located in XDG_CONFIG_HOME. That variable might
# not be available when .zshrc is loaded so a concrete path is needed to be
# set in that file. Since `pont` knows these variables by the time it gets
# here, I can just dynamically create the `.zshenv` file

if [ -L "$HOME/.zshenv" ]; then
	rm "$HOME/.zshenv"
fi

if [ -e "$HOME/.zshenv" ] &&
	! grep -q "# THIS FILE WAS GENERATED BY A DOTMODULE" "$HOME/.zshenv"; then
	echo "existing ~/.zshenv file renamed to ~/.zshenv.bak"
	mv "$HOME/.zshenv" "$HOME/.zshenv.bak"
fi

# ? $XDG_CONFIG_HOME is intentionally evaluated in this file
cat <<EOF > "$HOME/.zshenv"
#!/bin/zsh
# THIS FILE WAS GENERATED BY A DOTMODULE
# This is here for compatibility reasons, using a login manager, this is not
# needed, but when logging directly into zsh, systemd envs are not available

# Minimal ZSH Environment
if [ -e "$XDG_CONFIG_HOME/environment.d/20-zshenv.conf" ]; then
	export XDG_CACHE_HOME="$XDG_CACHE_HOME"
	export XDG_CONFIG_HOME="$XDG_CONFIG_HOME"
	# shellcheck disable=SC1090,SC1091
	. "$XDG_CONFIG_HOME/environment.d/20-zshenv.conf"
fi
# rest is loaded by the startup scripts in ZDOTDIR, set in 20-zshenv.conf
# inluding the ~/.profile file (which in turn loads the entire environment)

# Windsurf/VS Code IDE terminals don't support job control (setopt monitor),
# which gitstatus requires. Disable it early to avoid a 5s timeout on init.
if [[ -n "\$VSCODE_PID" ]]; then
	export POWERLEVEL9K_DISABLE_GITSTATUS=true
fi

# Non-interactive shells (e.g. IDE tool runners) skip ZDOTDIR/.zshrc, so
# loadenv never runs and tools like node/fnm/pnpm are missing from PATH.
# For interactive shells, .zshrc already sources ~/.profile after plugins.
if [[ ! -o interactive ]]; then
	[ -f "\$HOME/.profile" ] && QUIET=1 . "\$HOME/.profile"
fi
EOF
