#!/bin/sh

# the XDG setup needs to be loaded manually during startup, the first file
# zsh laods under our control is ~/.zshenv here, I tell it where it can find
# the zshrc file. But both are located in XDG_CONFIG_HOME. That variable might
# not be available when .zshrc is loaded so a concrete path is needed to be
# set in that file. Since `pont` knows these variables by the time it gets
# here, I can just dynamically create the `.zshenv` file

if [ -e "$HOME/.zshenv" ] &&
	! grep -q "# THIS FILE WAS GENERATED BY A DOTMODULE" "$HOME/.zshenv"; then
	echo "existing ~/.profile file renamed to ~/.profile.bak"
	mv "$HOME/.zshenv" "$HOME/.zshenv.bak"
fi

cat <<EOF > "$HOME/.zshenv"
#!/bin/zsh
# THIS FILE WAS GENERATED BY A DOTMODULE
# This is here for compatibility reasons, using a login manager, this is not
# needed, but when logging directly into zsh, systemd envs are not available

# ZSH Environment
if [ -e \"$XDG_CONFIG_HOME/environment.d/20-zshenv.conf\" ]; then
	# shellcheck disable=SC1090,SC1091
	. \"$XDG_CONFIG_HOME/environment.d/20-zshenv.conf\"
fi
# rest is loaded by the startup scripts in ZDOTDIR, set in 20-zshenv.conf
# inluding the ~/.profile file (which in turn loads the entire environment)
EOF
