#!/bin/sh

appendabsent '*.rs merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.ts merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.tsx merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.js merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.jsx merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.html merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.htm merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.json merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.md merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.py merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.lua merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"

appendabsent '*.java merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.properties merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.yml merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.yaml merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"
appendabsent '*.toml merge=mergiraf' "$XDG_CONFIG_HOME/git/attributes"

# Generated using `mergiraf languages --gitattributes` with `mergiraf 0.17.0`
# *.java merge=mergiraf
# *.properties merge=mergiraf
# *.kt merge=mergiraf
# *.rs merge=mergiraf
# *.go merge=mergiraf
# go.mod merge=mergiraf
# go.sum merge=mergiraf
# go.work.sum merge=mergiraf
# *.ini merge=mergiraf
# *.js merge=mergiraf
# *.jsx merge=mergiraf
# *.mjs merge=mergiraf
# *.cjs merge=mergiraf
# *.json merge=mergiraf
# *.yml merge=mergiraf
# *.yaml merge=mergiraf
# pyproject.toml merge=mergiraf
# *.toml merge=mergiraf
# *.html merge=mergiraf
# *.htm merge=mergiraf
# *.xhtml merge=mergiraf
# *.xml merge=mergiraf
# *.c merge=mergiraf
# *.h merge=mergiraf
# *.cc merge=mergiraf
# *.hh merge=mergiraf
# *.cpp merge=mergiraf
# *.hpp merge=mergiraf
# *.cxx merge=mergiraf
# *.hxx merge=mergiraf
# *.c++ merge=mergiraf
# *.h++ merge=mergiraf
# *.mpp merge=mergiraf
# *.cppm merge=mergiraf
# *.ixx merge=mergiraf
# *.tcc merge=mergiraf
# *.cs merge=mergiraf
# *.dart merge=mergiraf
# *.dts merge=mergiraf
# *.scala merge=mergiraf
# *.sbt merge=mergiraf
# *.ts merge=mergiraf
# *.mts merge=mergiraf
# *.cts merge=mergiraf
# *.tsx merge=mergiraf
# *.py merge=mergiraf
# *.php merge=mergiraf
# *.phtml merge=mergiraf
# *.php3 merge=mergiraf
# *.php4 merge=mergiraf
# *.php5 merge=mergiraf
# *.phps merge=mergiraf
# *.phpt merge=mergiraf
# *.sol merge=mergiraf
# *.lua merge=mergiraf
# *.rb merge=mergiraf
# *.ex merge=mergiraf
# *.exs merge=mergiraf
# *.nix merge=mergiraf
# *.sv merge=mergiraf
# *.svh merge=mergiraf
# *.md merge=mergiraf
# *.hcl merge=mergiraf
# *.tf merge=mergiraf
# *.tfvars merge=mergiraf
# *.ml merge=mergiraf
# *.mli merge=mergiraf
# *.hs merge=mergiraf
# *.mk merge=mergiraf
# Makefile merge=mergiraf
# GNUmakefile merge=mergiraf
# *.bzl merge=mergiraf
# *.bazel merge=mergiraf
# BUILD merge=mergiraf
# WORKSPACE merge=mergiraf
# *.cmake merge=mergiraf
# CMakeLists.txt merge=mergiraf
# *.f merge=mergiraf
# *.for merge=mergiraf
# *.f90 merge=mergiraf
# *.R merge=mergiraf
# *.r merge=mergiraf
# .Rprofile merge=mergiraf
# requirements.txt merge=mergiraf
# requirements-dev.txt merge=mergiraf
# requirements-docs.txt merge=mergiraf
# requirements-test.txt merge=mergiraf
