#!/bin/sh

# Import from $1 or from the default place

gpg --import "${1-$HOME}/pass-private-key.asc"

# Then initialize pass with the last added key
pass init "$(gpg --list-secret-keys |
	grep "^      " |
	tail -1 |
	sed 's/^      //')"
