#!/bin/sh

# Copy the resulting file after export to a more secure place

mkdir -p "${1-$HOME}"

gpg --armor --export-secret-keys "$(cat "$PASSWORD_STORE_DIR/.gpg-id")" \
	>"${1-$HOME}/pass-private-key.asc"

gpg --armor --export "$(cat "$PASSWORD_STORE_DIR/.gpg-id")" \
	>"${1-$HOME}/pass-public-key.asc"
