#!/bin/sh

TARGET=${1:-"$HOME/.ssh"}

# Original from
# https://gist.github.com/kevinadi/96090f6f9973ff8c2d019bbe0d9a0f70

# Generate self signed root CA cert
openssl req -nodes -x509 -newkey rsa:4086 -keyout "$TARGET/ca.key" \
	-out "$TARGET/ca.crt" \
	-subj "/C=HU/ST=Budapest/L=Budapest/O=aegis/OU=root/CN=$(hostname -f)\
/emailAddress=alexaegis@gmail.com"

# Generate server cert to be signed
openssl req -nodes -newkey rsa:4086 -keyout "$TARGET/server.key" \
	-out "$TARGET/server.csr" -subj "/C=HU/ST=Budapest/L=Budapest/\
O=aegis/OU=server/CN=$(hostname -f)/emailAddress=alexaegis@gmail.com"

# Sign the server cert
openssl x509 -req -in "$TARGET/server.csr" -CA "$TARGET/ca.crt" \
	-CAkey "$TARGET/ca.key" -CAcreateserial -out "$TARGET/server.crt"

# Create server PEM file
cat "$TARGET/server.key" "$TARGET/server.crt" >"$TARGET/server.pem"

# Generate client cert to be signed
openssl req -nodes -newkey rsa:4086 -keyout "$TARGET/client.key" \
	-out "$TARGET/client.csr" -subj "/C=HU/ST=Budapest/L=Budapest/\
O=aegis/OU=client/CN=$(hostname -f)/emailAddress=alexaegis@gmail.com"

# Sign the client cert
openssl x509 -req -in "$TARGET/client.csr" -CA "$TARGET/ca.crt" \
	-CAkey "$TARGET/ca.key" -CAserial "$TARGET/ca.srl" -out "$TARGET/client.crt"

# Create client PEM file
cat "$TARGET/client.key" "$TARGET/client.crt" >"$TARGET/client.pem"

# Create clientPFX file (for Java, C#, etc)
openssl pkcs12 -inkey "$TARGET/client.key" -in "$TARGET/client.crt" \
	-export -out "$TARGET/client.pfx"
