#!/bin/sh

# Generates a non-password protected rsa key pair

NAME=${1:-"id_rsa"}
TARGET=${2:-"$HOME/.ssh"}

RSA_PRIV="$TARGET/$NAME"
ssh-keygen -t rsa -b 4096 -N "" -C "$USER@$(hostname)" -f "$RSA_PRIV"

chmod 400 "$RSA_PRIV" "$RSA_PRIV.pub"
