#!/bin/sh
# From: https://askubuntu.com/questions/889344/command-to-perform-a-recursive-chmod-to-make-all-sh-files-within-a-directory-ex
# Adds execute rights to every .sh file under this
# TODO: Experiment with grep and shebang based solution
# TODO: grep -rIzl '^#!' ./
# TODO: skip everything in git submodules
find ./ -type f -regex ".*\.\(sh\|zsh\|bash\|fish\|dash\)" -exec chmod +x {} \;
