#!/bin/sh
# Loads every `*.env` files in the home and in the .env.d folders
# And every `*.alias` files in the home and in the .alias.d folders
# And every `*.$LOADENV_RC_EXTS` files in the home and in the .rc.d folders
[ ! "$QUIET" ] && echo "Loading Environment"
set -a

# force xdg settings from module if available
script_location=$(
	cd "${0%\/*}" 2>/dev/null || exit
	pwd
)
if [ "$script_location" ] && [ -L "$script_location/loadenv" ]; then
	script_link_location=$(readlink "$script_location/loadenv")
	if ! [ "${script_link_location#\/}" = "$script_link_location" ]; then
		# absulte link
		script_location="$script_link_location"
	else
		# relative link
		script_location="$script_location/$script_link_location"
	fi
	script_location=${script_location%\/*} # cut filename
fi
if [ "$script_location" ] && [ -e "$script_location/../../xdg/e.user.sh" ]; then
	current_pwd=$(pwd)
	cd "$script_location/../../xdg" || exit 1
	set -a
	# shellcheck source=/dev/null
	. "$script_location/../../xdg/e.user.sh"
	set +a
	cd "$current_pwd" || exit 1
fi


# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME" REGEX=".*\.env" . "$XDG_BIN_HOME/sourcein"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME/environment.d" REGEX=".*\.env" . "$XDG_BIN_HOME/sourcein"

# shellcheck source=/dev/null
# Load if no already loaded
if [ ! "$CONF_LOADED" ] || [ "$LOAD_CONF" ]; then
	[ ! "$QUIET" ] &&`` echo "Manually loading *.conf files!"
	DIR="$XDG_CONFIG_HOME/environment.d" REGEX=".*\.conf" . \
		"$XDG_BIN_HOME/sourcein"
fi

[ ! "$QUIET" ] && echo "Loading Aliases"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME" REGEX=".*\.alias" . "$XDG_BIN_HOME/sourcein"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME/alias.d" REGEX=".*\.alias" . "$XDG_BIN_HOME/sourcein"

[ ! "$QUIET" ] && echo "Loading every" \
	".$(echo "${LOADENV_RC_EXTS:-sh}" | sed 's@ @ .@g') rc files"
loadenv_rc_exts=${LOADENV_RC_EXTS:-sh}
for ext in $(echo "$loadenv_rc_exts" | tr ' ' '\n'); do
	loadenv_source_rc=
	case "$ext" in
		sh)
			loadenv_source_rc=1
			;;
		bash)
			[ "$BASH_VERSION" ] && loadenv_source_rc=1
			;;
		zsh)
			[ "$ZSH_VERSION" ] && loadenv_source_rc=1
			;;
	esac
	[ "$loadenv_source_rc" ] || continue

	# shellcheck disable=SC1091
	DIR="$XDG_CONFIG_HOME/rc.d" REGEX=".*\.$ext" . "$XDG_BIN_HOME/sourcein"
done

set +a
