#!/bin/sh
# Loads every `*.env` files in the home and in the .env.d folders
# And every `*.alias` files in the home and in the .alias.d folders
# And every `*.$LOADENV_RC_EXTS` files in the home and in the .rc.d folders
[ ! "$QUIET" ] && echo "Loading Environment"
set -a

# force xdg settings from module if available
script_location=$(
	cd "${0%\/*}" || exit
	pwd
)
if [ -L "$script_location/loadenv" ]; then
	script_link_location=$(readlink "$script_location/loadenv")
	if ! [ "${script_link_location#\/}" = "$script_link_location" ]; then
		# absulte link
		script_location="$script_link_location"
	else
		# relative link
		script_location="$script_location/$script_link_location"
	fi
	script_location=${script_location%\/*} # cut filename
fi
if [ -e "$script_location/../../xdg/e.user.sh" ]; then
	cd "$script_location/../../xdg" || exit 1
	set -a
	# shellcheck source=/dev/null
	. "$script_location/../../xdg/e.user.sh"
	set +a
fi


# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME" REGEX=".*\.env" . "$XDG_BIN_HOME/sourcein"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME/environment.d" REGEX=".*\.env" . "$XDG_BIN_HOME/sourcein"

# shellcheck source=/dev/null
# Load if no already loaded
if [ ! "$CONF_LOADED" ] || [ "$LOAD_CONF" ]; then
	[ ! "$QUIET" ] &&`` echo "Manually loading *.conf files!"
	DIR="$XDG_CONFIG_HOME/environment.d" REGEX=".*\.conf" . \
		"$XDG_BIN_HOME/sourcein"
fi

[ ! "$QUIET" ] && echo "Loading Aliases"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME" REGEX=".*\.alias" . "$XDG_BIN_HOME/sourcein"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME/alias.d" REGEX=".*\.alias" . "$XDG_BIN_HOME/sourcein"

[ ! "$QUIET" ] && echo "Loading every" \
	".$(echo "${LOADENV_RC_EXTS:-sh}" | sed 's@ @ .@g') rc files"
# while earlier an advanced regex was used to read all the extensions together
# a simple solution had to be implemented because BSD find did not support it
for ext in $(echo $LOADENV_RC_EXTS | tr ' ' '\n'); do
	DIR="$XDG_CONFIG_HOME/rc.d" REGEX=".*\.$ext" . "$XDG_BIN_HOME/sourcein"
done

set +a
