#!/bin/sh
# Loads every `*.env` files in the home and in the .env.d folders
# And every `*.alias` files in the home and in the .alias.d folders
# And every `*.$LOADENV_RC_EXTS` files in the home and in the .rc.d folders

[ ! "$QUIET" ] && echo "Loading Environment"
set -a
# ? We actually can rely on the absolute path of `sourcein` here because
# ? it is added by this module
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME" REGEX=".*\.env" . "$XDG_BIN_HOME/sourcein"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME/env.d" REGEX=".*\.env" . "$XDG_BIN_HOME/sourcein"

[ ! "$QUIET" ] && echo "Loading Aliases"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME" REGEX=".*\.alias" . "$XDG_BIN_HOME/sourcein"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME/alias.d" REGEX=".*\.alias" . "$XDG_BIN_HOME/sourcein"

[ ! "$QUIET" ] && echo "Loading every \
	.$(echo "${LOADENV_RC_EXTS:-sh}" | sed 's@ @ .@g') rc files"
# shellcheck source=/dev/null
DIR="$XDG_CONFIG_HOME/rc.d" \
	REGEX=".*\.\($(echo "${LOADENV_RC_EXTS:-sh}" | sed 's@ @\\|@g')\)" \
	. "$XDG_BIN_HOME/sourcein"

set +a
