#!/bin/sh

# Updates packages

if command -v apt > /dev/null; then
    echo "Updating packages using apt..."
    sudo apt update
	sudo apt upgrade -y
fi

if command -v brew > /dev/null; then
    echo "Updating packages using apt..."
	${SUDO_USER:+sudo -u $SUDO_USER} brew update
	${SUDO_USER:+sudo -u $SUDO_USER} brew upgrade
fi

if command -v pacman > /dev/null; then
    echo "Updating packages using pacman..."
    sudo pacman -Syu --noconfirm
fi

if command -v aura > /dev/null; then
    echo "Updating AUR packages using aura..."
	${SUDO_USER:+sudo -u $SUDO_USER} aura -Ayu --noconfirm # update AUR packages
	${SUDO_USER:+sudo -u $SUDO_USER} aura -Bc --noconfirm # remove stale snapshots
	${SUDO_USER:+sudo -u $SUDO_USER} aura check # diagnostics
fi

if command -v dnf > /dev/null; then
    echo "Updating packages using dnf..."
    sudo dnf upgrade --refresh -y
fi

if command -v zypper > /dev/null; then
    echo "Updating packages using zypper..."
    sudo zypper refresh
	sudo zypper update -y
fi

if command -v xbps-install > /dev/null; then
    echo "Updating packages using xbps..."
    sudo xbps-install -Su
fi


