#!/bin/sh
# Simple POSIX compatible password prompt

message=${1-"Please enter password"}
echo "$message"
tries=0
max_tries=3
while [ $tries -lt $max_tries ]; do
	if  [ $tries -gt 0 ]; then
		echo "Tries: $tries / $max_tries"
	fi
	tries=$((tries+1))

	printf "Password: "
	stty_orig=$(stty -g)
	stty -echo
	read password
	stty $stty_orig
	echo ""

	printf "Password (again): "
	stty_orig=$(stty -g)
	stty -echo
	read password2
	stty $stty_orig
	echo ""

	if [ "$password" = "$password2" ]; then
		echo $password;
		break;
	else
		echo "Please try again"
	fi
done
