#!/bin/sh

# TODO: password is visible because -s is non-posix, can't use it: read: Illegal option -s

echo "$0"
tries=0
while [ $tries -lt 3 ]; do
	tries=$((tries+1))
	echo $tries
	read -s "Password: " password
	read -s "Password (again): " password2
	if [ "$password" = "$password2" ]; then
		echo $password;
		break;
	else
		echo "Please try again"
	fi
done
