#!/bin/sh

# Source: https://stackoverflow.com/questions/22097130

echo "Cleaning up broken symlinks in: ${1-$PWD}"
find "${1-$PWD}" -type l -exec \
	sh -c 'for x; do [ -e "$x" ] || rm "$x"; done' _ {} +
