#!/bin/sh
# Yanked from https://github.com/WhyNotHugo/grub-holdshift

set -e

# grub-mkconfig helper script.
# Copyright (C) 2006,2007,2008,2009  Free Software Foundation, Inc.
# Copyright (C) 2013 Hugo Osvaldo Barrera
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

prefix="/usr"
# shellcheck disable=SC2034
exec_prefix="${prefix}"
datarootdir="${prefix}/share"

export TEXTDOMAIN=grub
export TEXTDOMAINDIR="${datarootdir}/locale"

# shellcheck disable=SC1090
. "${datarootdir}/grub/grub-mkconfig_lib"

# shellcheck disable=SC2034
found_other_os=

if [ "x${GRUB_HIDDEN_TIMEOUT_QUIET}" = "xtrue" ]; then
  verbose=
else
  verbose=" --verbose"
fi

cat <<EOF
if [ "x\${timeout}" != "x-1" ]; then
  if keystatus; then
    if keystatus --shift; then
      set timeout=-1
    else
      set timeout=0
    fi
  else
    if sleep$verbose --interruptible 0 ; then
      set timeout=0
    fi
  fi
fi
EOF
