#!/bin/sh

# Remove autogenerated files
if [ -e "$HOME/.bashrc" ]; then
	rm "$HOME/.bashrc"
fi

if [ -e "$HOME/.bash_logout" ]; then
	rm "$HOME/.bash_logout"
fi

if [ -e "$HOME/.bash_profile" ]; then
	rm "$HOME/.bash_profile"
fi
