#!/bin/sh
# create gpg keys
# TODO set the default through configs
default_comment="Generic key"

echo "%echo Generating an OpenPGP key
Key-Type: RSA
Key-Length: 4096
Subkey-Type: RSA
Subkey-Length: 4096
Name-Real: Győri Sándor
Name-Comment: ${1-$default_comment}
Name-Email: alexaegis@pm.me
Expire-Date: 0
%commit
%echo done
" >gpgconf.temp

gpg --batch --generate-key gpgconf.temp

rm gpgconf.temp

# gpg --list-secret-keys | grep "^      " | tail -1
