#!/bin/sh

# First redo the file with all the normal keygrips
gpg -K --with-keygrip |
	grep Keygrip |
	awk '{ print $3 }' > "$XDG_CONFIG_HOME"/pam-gnupg

# Then append the ssh keygrips to the end
gpg-connect-agent 'keyinfo --ssh-list' /bye |
	sed '/^OK$/d' |
	awk '{ print $3 }' >> "$XDG_CONFIG_HOME"/pam-gnupg
