#!/bin/sh

if command -v systemctl >/dev/null; then
	systemctl daemon-reload

	if systemctl is-active --quiet "$1"; then
		systemctl reload "$1" || systemctl restart "$1"
	elif systemctl is-enabled --quiet "$1"; then
		systemctl start "$1"
	else
		systemctl enable --now "$1"
	fi

fi
