name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Environment
        run: |
          echo ::set-env name=WEEK::$(date +%V)
          echo ::set-env name=SUDO_AVAIL::$(if command -v sudo \
            2> /dev/null; then echo 1; fi)
      - name: Update repositories
        run: |
          ${SUDO_AVAIL:+sudo} apt-get update
      - name: Install dependencies
        run: |
          ${SUDO_AVAIL:+sudo} apt-get install -y make
      - name: Cache shellcheck
        id: cache-shellcheck
        uses: actions/cache@v1
        with:
          path: shellcheck-stable
          key: ${{ runner.os }}-shellcheck-${WEEK}
      - name: Install shellcheck download only dependencies
        if: steps.cache-shellcheck.outputs.cache-hit != 'true'
        run: |
          ${SUDO_AVAIL:+sudo} apt-get install -y wget tar xz-utils
      - name: Download shellcheck and dependencies
        if: steps.cache-shellcheck.outputs.cache-hit != 'true'
        run: |
          wget -qO- "https://github.com/koalaman/shellcheck/releases\
          /download/stable\
          /shellcheck-stable.linux.x86_64.tar.xz" | tar -xJv
          ${SUDO_AVAIL:+sudo} \
            cp "shellcheck-stable/shellcheck" /usr/bin/
      - name: Install shellcheck
        run: |
          ${SUDO_AVAIL:+sudo} \
            cp "shellcheck-stable/shellcheck" /usr/bin/
      - name: Check shellcheck version
        run: shellcheck --version
      - name: Lint
        run: make lint
